sudo: false
cache:
  directories:
  - $HOME/.m2
jdk: oraclejdk7
language: android
android:
  components:
    - android-19
    - android-22
    - android-23
    - build-tools-22.0.0
    - build-tools-22.0.1
    - build-tools-21.1.2
    - build-tools-23.0.1
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

before_script:

  # Install Android NDK 10b
  # Note: There is now a difference between Target architecture and Platform architecture. What SHOULD they be?
  - NDK_ARCH=""
  - NDK_PLAT="32"
  - if [ `uname -m` = x86_64 ]; then NDK_ARCH=_64; NDK_PLAT=32; fi
  - FILE="android-ndk${NDK_PLAT}-r10b-linux-x86${NDK_ARCH}.tar.bz2"
  - wget http://dl.google.com/android/ndk/${FILE}
  - tar xjf ${FILE}
  - export ANDROID_NDK_HOME=$PWD/android-ndk-r10b



gradle build
